### ISSUE TITLE
the bot is not working

### ISSUE THREAD

**Issue by Bogghi** [dartungar/text-to-notion-bot#1]
HI,
I use this awesome bot to make quick input into my note taking system but today i've shared a link and it wasn't inserting into it, even the command no longer work. 
Is this related to the bot or maybe the custom API?

![telegram](https://user-images.githubusercontent.com/11005947/83436718-9f8d8100-a43e-11ea-89a1-d4723b64d69b.png)

Best regards.

**Comment by dartungar** [comment]
Bot was offline due to some server issues (mainly me not making proper restart system). It is online now.
